// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zoorganize.Database;

#nullable disable

namespace Zoorganize.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210093928_ChnangeSomeThings")]
    partial class ChnangeSomeThings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("AnimalEnclosureSpecies", b =>
                {
                    b.Property<Guid>("AllowedSpeciesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnimalEnclosureId")
                        .HasColumnType("TEXT");

                    b.HasKey("AllowedSpeciesId", "AnimalEnclosureId");

                    b.HasIndex("AnimalEnclosureId");

                    b.ToTable("AnimalEnclosureSpecies");
                });

            modelBuilder.Entity("SpeciesStaff", b =>
                {
                    b.Property<Guid>("AuthorizedSpeciesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorizedSpeciesId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("SpeciesStaff");
                });

            modelBuilder.Entity("StaffStaffRooms", b =>
                {
                    b.Property<Guid>("AuthorizedStaffId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StaffRoomsId")
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorizedStaffId", "StaffRoomsId");

                    b.HasIndex("StaffRoomsId");

                    b.ToTable("StaffStaffRooms");
                });

            modelBuilder.Entity("StaffVisitorRoom", b =>
                {
                    b.Property<Guid>("StaffId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VisitorRoomId")
                        .HasColumnType("TEXT");

                    b.HasKey("StaffId", "VisitorRoomId");

                    b.HasIndex("VisitorRoomId");

                    b.ToTable("StaffVisitorRoom");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aggressive")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ArrivalDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BehavioralNotes")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentEnclosureId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EnclosureAssignedSince")
                        .HasColumnType("TEXT");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InQuarantine")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNeutered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("KeeperId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresSeparation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CurrentEnclosureId");

                    b.HasIndex("KeeperId");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.ExternalZooStay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZooName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("ExternalZooStays");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double?>("AreaInSquareMeters")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Zoorganize.Database.Models.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDangerous")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSolitaryByNature")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxGroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxHumidity")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxTemperature")
                        .HasColumnType("REAL");

                    b.Property<double>("MinAreaPerAnimal")
                        .HasColumnType("REAL");

                    b.Property<int?>("MinGroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MinHumidity")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinTemperature")
                        .HasColumnType("REAL");

                    b.Property<int>("RequiredSecurityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresClimbingStructures")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresOutdoorAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresShelter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresSpecialPermit")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresWaterFeature")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScientificName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ExitDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<float>("YearlySalary")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.VeterinaryAppointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("VeterinaryAppointments");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.Zoo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Zoos");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.AnimalEnclosure", b =>
                {
                    b.HasBaseType("Zoorganize.Database.Models.Room");

                    b.Property<bool>("HasClimbingStructures")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasShelter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasWaterFeature")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEscapeProof")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOutdoor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxHumidity")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxTemperature")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinHumidity")
                        .HasColumnType("REAL");

                    b.Property<double>("MinTemperature")
                        .HasColumnType("REAL");

                    b.Property<bool>("MixedSpeciesAllowed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecurityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TemperatureControlled")
                        .HasColumnType("INTEGER");

                    b.ToTable("AnimalEnclosures");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.StaffRooms", b =>
                {
                    b.HasBaseType("Zoorganize.Database.Models.Room");

                    b.ToTable("StaffRooms");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.VisitorRoom", b =>
                {
                    b.HasBaseType("Zoorganize.Database.Models.Room");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("VisitorRooms");
                });

            modelBuilder.Entity("AnimalEnclosureSpecies", b =>
                {
                    b.HasOne("Zoorganize.Database.Models.Species", null)
                        .WithMany()
                        .HasForeignKey("AllowedSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoorganize.Database.Models.AnimalEnclosure", null)
                        .WithMany()
                        .HasForeignKey("AnimalEnclosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpeciesStaff", b =>
                {
                    b.HasOne("Zoorganize.Database.Models.Species", null)
                        .WithMany()
                        .HasForeignKey("AuthorizedSpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoorganize.Database.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StaffStaffRooms", b =>
                {
                    b.HasOne("Zoorganize.Database.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("AuthorizedStaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoorganize.Database.Models.StaffRooms", null)
                        .WithMany()
                        .HasForeignKey("StaffRoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StaffVisitorRoom", b =>
                {
                    b.HasOne("Zoorganize.Database.Models.Staff", null)
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zoorganize.Database.Models.VisitorRoom", null)
                        .WithMany()
                        .HasForeignKey("VisitorRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoorganize.Database.Models.Animal", b =>
                {
                    b.HasOne("Zoorganize.Database.Models.AnimalEnclosure", "CurrentEnclosure")
                        .WithMany("Animals")
                        .HasForeignKey("CurrentEnclosureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zoorganize.Database.Models.Staff", "Keeper")
                        .WithMany("AssignedAnimals")
                        .HasForeignKey("KeeperId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Zoorganize.Database.Models.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentEnclosure");

                    b.Navigation("Keeper");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.ExternalZooStay", b =>
                {
                    b.HasOne("Zoorganize.Database.Models.Animal", "Animal")
                        .WithMany("ExternalZooStays")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.VeterinaryAppointment", b =>
                {
                    b.HasOne("Zoorganize.Database.Models.Animal", "Animal")
                        .WithMany("VeterinaryAppointments")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.AnimalEnclosure", b =>
                {
                    b.HasOne("Zoorganize.Database.Models.Room", null)
                        .WithOne()
                        .HasForeignKey("Zoorganize.Database.Models.AnimalEnclosure", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoorganize.Database.Models.StaffRooms", b =>
                {
                    b.HasOne("Zoorganize.Database.Models.Room", null)
                        .WithOne()
                        .HasForeignKey("Zoorganize.Database.Models.StaffRooms", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoorganize.Database.Models.VisitorRoom", b =>
                {
                    b.HasOne("Zoorganize.Database.Models.Room", null)
                        .WithOne()
                        .HasForeignKey("Zoorganize.Database.Models.VisitorRoom", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zoorganize.Database.Models.Animal", b =>
                {
                    b.Navigation("ExternalZooStays");

                    b.Navigation("VeterinaryAppointments");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.Staff", b =>
                {
                    b.Navigation("AssignedAnimals");
                });

            modelBuilder.Entity("Zoorganize.Database.Models.AnimalEnclosure", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
